using System;
using System.IO;

namespace OsuCursorWin;

/// <summary>
/// Logging helper. The entry point (Program.Main) is generated by the WinUI 3
/// XAML compiler in App.g.i.cs, so we must not define our own Program class.
/// </summary>
internal static class AppLog
{
    internal static string LogPath => Path.Combine(Path.GetTempPath(), "OsuCursorWin.log");

    internal static void Log(string message)
    {
        try
        {
            File.AppendAllText(LogPath, $"{DateTime.Now:O} {message}{Environment.NewLine}");
        }
        catch { }
    }
}